version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    volumes:
      - ./files:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks: [ "service_network" ]
  cache:
    container_name: rediscache
    image: redis:latest
    ports:
      - "6379:6379"
    networks: [ "service_network" ]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
        - "8080"
    ports:
      - "8080:8080"
    networks: [ "service_network" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: cache
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - cache
networks:
  microservices:
    name: service_network