version: '3'
services:
  mysql-container:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
  redis-container:
    image: redis:latest
    ports:
      - "6379:6379"
  spring-boot-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
      - redis-container
